### ISSUE TITLE
Issue with the statement 

### ISSUE THREAD

**Issue by TheMoominTroll** [crashpeshal/learnGit#2]
> https://github.com/crashpeshal/learnGit/blob/a5b1a7f99a31f5622f1ffeadfa9d4602a4b36865/Getting%20Started%20With%20Github%20and%20Git%20Bash.txt#L92
> You have to do : git add <filename> to put that file to staging area only then u can commit
> The git doesn't push to cloud until you set remote; also rename cloud as internet repository.
> 

> https://github.com/crashpeshal/learnGit/blob/a5b1a7f99a31f5622f1ffeadfa9d4602a4b36865/Getting%20Started%20With%20Github%20and%20Git%20Bash.txt#L18
> We can also clone with ssh which is what i prefer.

> https://github.com/crashpeshal/learnGit/blob/a5b1a7f99a31f5622f1ffeadfa9d4602a4b36865/Getting%20Started%20With%20Github%20and%20Git%20Bash.txt#L7
> Refer linking as just cloning. It is just downloading the repository and without correct user permission it is not linked to any changes in the internet repository.

> Avoid naming files with spaces and it is preferable and more customizable to write in markdown rather than txt.

**Comment by crashpeshal** [comment]
1. I literally copy pasted your previous suggestion with just some text formatting. Plus I've already mentioned the process of adding, committing and pushing.
2. By the mentioned process of cloning/linking it resembles the same idea. Terminology might create conflict but after cloning the internet repo to the local machine (by this time you should already have signed in with the same github account that the repo was made on), you can work on your files and add,commit and push without the hassle of initialization.

**Comment by crashpeshal** [comment]
1. I already explained it pretty well in the beginning. Your issue is completely irrelevant to what I actually wrote about add, commit and push.
2.That's why I mentioned you should already be logged in by the time you clone. I already clarified everything.
