### ISSUE TITLE
use a markdown file instead

### ISSUE THREAD

**Issue by Eclipsu** [crashpeshal/learnGit#3]
Instead of making .txt file you can make readme.md file which will be shown in your repo.

**Comment by crashpeshal** [comment]
Already suggested, I'll be working on it.

**Comment by TheMoominTroll** [comment]
@Eclipsu instead of making duplicate issues; fix the issue on your repo that i mentioned; about being the screenshot not showing 

just add : ! [alt] (link) for image of neofetch ( without spaces ).

@crashpeshal Just do your work i will be here to create issues.

**Comment by Eclipsu** [comment]
sed
